# Generated by Django 5.1.7 on 2025-07-19 01:58

import django.db.models.deletion
import school.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='school.timestamp')),
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
            ],
            bases=('school.timestamp',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='school.timestamp')),
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
            ],
            bases=('school.timestamp',),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.timestamp')),
                ('assignment_file', models.FileField(upload_to=school.models.Assignment.assignment_upload_path)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('school.timestamp',),
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.timestamp')),
                ('file', models.FileField(upload_to='assignment/students')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_submissions', to=settings.AUTH_USER_MODEL)),
                ('sub_assingment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.assignment')),
            ],
            bases=('school.timestamp',),
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='school.timestamp')),
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50, unique=True)),
                ('total_students', models.PositiveIntegerField()),
                ('location', models.TextField()),
                ('class_coordinator', models.ForeignKey(blank=True, limit_choices_to={'role': 'Stu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('class_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'T'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_class', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('school.timestamp',),
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom'),
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AttandanceSession',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.timestamp')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom')),
                ('t_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attandance', to='school.subject')),
            ],
            options={
                'unique_together': {('teacher', 'class_name', 't_subject')},
            },
            bases=('school.timestamp',),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.subject'),
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.timestamp')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.classroom')),
                ('subjects', models.ManyToManyField(related_name='subject_teachers', to='school.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'T'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('school.timestamp',),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.timestamp')),
                ('time_table', models.FileField(upload_to='timetable/')),
                ('klass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='school.classroom')),
            ],
            bases=('school.timestamp',),
        ),
        migrations.CreateModel(
            name='AttandanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Absent'), ('P', 'Present')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attandance_records', to=settings.AUTH_USER_MODEL)),
                ('atd_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attandance_records', to='school.attandancesession')),
            ],
            options={
                'unique_together': {('atd_session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.timestamp')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STU'}, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL)),
                ('subject_marks', models.ManyToManyField(to='school.subjectmark')),
                ('s_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
            options={
                'unique_together': {('student', 's_subject')},
            },
            bases=('school.timestamp',),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.timestamp')),
                ('class_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrolled', to='school.classroom')),
                ('courses', models.ManyToManyField(to='school.course')),
                ('student', models.OneToOneField(limit_choices_to={'role': 'STU'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(to='school.subject')),
            ],
            options={
                'unique_together': {('student', 'class_room')},
            },
            bases=('school.timestamp',),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('class_name', 'subj')},
        ),
    ]
