# Generated by Django 5.1.7 on 2025-07-19 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='total_students',
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_date_sub',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
