# Generated by Django 5.1.7 on 2025-07-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='monthly_fee',
            new_name='tuestion_fee',
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='exam_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='extra',
            field=models.FloatField(default=0),
        ),
    ]
