# Generated by Django 5.1.7 on 2025-07-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_schoolclass_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'section')},
        ),
    ]
