# Generated by Django 5.1.7 on 2025-07-19 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/images/')),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/images/')),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('maried', models.BooleanField(default=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
