# Generated by Django 5.1.7 on 2025-07-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='email',
        ),
    ]
