# Generated by Django 5.1.7 on 2025-07-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ST', 'Student'), ('T', 'Teacher')], default='ST', max_length=3),
        ),
    ]
