# Generated by Django 5.1.7 on 2025-07-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='employee_id',
            new_name='id',
        ),
    ]
