# Generated by Django 5.1.7 on 2025-07-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_employee_id_teacherprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('is_admin', 'admin user only ')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
