# Generated by Django 5.1.7 on 2025-07-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fakemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakemodel',
            options={'default_permissions': (), 'managed': False, 'permissions': [('is_admin', 'admin user only '), ('my_profile', 'only profile user ')]},
        ),
    ]
