# Generated by Django 5.1.7 on 2025-07-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_fakemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakemodel',
            options={'default_permissions': (), 'managed': False, 'permissions': [('is_admin', 'admin user only ')]},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'permissions': [('my_profile', 'only profile user ')]},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'permissions': [('my_profile', 'only profile user ')]},
        ),
    ]
