# Generated by Django 5.1.7 on 2025-07-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_fakemodel_options_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakemodel',
            options={'default_permissions': (), 'managed': False, 'permissions': [('admin_only', 'admin user only ')]},
        ),
    ]
