# Generated by Django 5.1.7 on 2025-07-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_fakemodel_options'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='maried',
            new_name='married',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.schoolclass'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
