# Generated by Django 5.1.7 on 2025-07-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_maried_teacherprofile_married_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ST', 'Student'), ('T', 'Teacher'), ('A', 'Admin')], default='A', max_length=3),
        ),
    ]
